#!/usr/bin/env php
<?php

$content = file_get_contents(__DIR__ . '/abbreviations.fish');

$startTag = '[//]: # (aliases)';
$endTag = '[//]: # (/aliases)';

$markdownLines = [
    $startTag,
    '',
    '| Alias | Command |',
    '|------:|---------|'
];

function escapePipe($string)
{
    return str_replace('|', '\\|', $string);
}

if (preg_match_all('`^abbr\s+(?P<abbreviation>[^\s]+)\s+(?P<command>.*)$`m', $content, $lines, PREG_SET_ORDER)) {
    foreach ($lines as $line) {
        $markdownLines[] = sprintf('| %s | %s |', escapePipe($line['abbreviation']), escapePipe($line['command']));
    }
}

$markdownLines[] = '';
$markdownLines[] = $endTag;

$regex = sprintf('`^%s.*%s$`sm', preg_quote($startTag), preg_quote($endTag));

$markdown = implode("\n", $markdownLines);

file_put_contents(__DIR__ . '/README.md', preg_replace($regex, $markdown, file_get_contents(__DIR__ . '/README.md')));
