#!/usr/bin/env php
<?php

$readmeFilePath = __DIR__ . '/README.md';
$readmeContent = file_get_contents($readmeFilePath);

/**
 * PARSE ABBREVIATIONS
 */
$commandGroups = [];

$currentGroupIndex = 'Other';

foreach (file(__DIR__ . '/abbreviations.fish') as $line) {

    $line = trim($line);

    if (empty($line)) {
        continue;
    }

    if (0 === strpos($line, '#')) {
        $currentGroupIndex = trim(substr($line, 1));
    } elseif (0 === strpos($line, 'abbr ')) {
        list($void, $abbr, $command) = explode(' ', $line, 3);
        $commandGroups[$currentGroupIndex][$abbr] = str_replace('|', '\\|', $command);
    }
}

$lines = [];

foreach ($commandGroups as $groupLabel => $commands) {

    $line = [
        '    <thead><tr><th colspan="2" align="left">' . $groupLabel . '</th></tr></thead>',
        '    <tbody>'
    ];
    foreach ($commands as $abbr => $command) {
        $line[] = '        <tr><th align="right">' . $abbr . '</th><td>' . trim($command, '\'') . '</td></tr>';
    }
    $line[] = '    </tbody>';

    $lines[] = implode("\n", $line);
}

$startTag = '[//]: # (abbreviations)';
$endTag = '[//]: # (/abbreviations)';

$output = $startTag . "\n\n";
$output .= '<table>' . "\n";
$output .= implode("\n    <tr><td colspan=\"2\"></td></tr>\n", $lines);
$output .= "\n" . '</table>';
$output .= "\n\n" . $endTag;

$readmeContent = preg_replace(
    sprintf('`^%s.*%s$`sm', preg_quote($startTag), preg_quote($endTag)),
    $output,
    $readmeContent
);

/**
 * PARSE COMMANDS
 */

$lines = [];

foreach (scandir(__DIR__ . '/functions') as $fileName) {

    $filePath = __DIR__ . '/functions/' . $fileName;

    if (!is_file($filePath)) {
        continue;
    }

    $fileContent = file_get_contents($filePath);

    if (!preg_match('`^#doc(.*)#enddoc$`ms', $fileContent, $match)) {
        continue;
    }

    $lines[] = '';
    $lines[] = '#### ' . basename($fileName, '.fish');
    $lines[] = '';
    $lines[] = preg_replace('`^# ?`m', '', trim($match[1]));
}

$startTag = '[//]: # (commands)';
$endTag = '[//]: # (/commands)';

array_unshift($lines, $startTag);
array_push($lines, '', $endTag);

$readmeContent = preg_replace(
    sprintf('`^%s.*%s$`sm', preg_quote($startTag), preg_quote($endTag)),
    implode("\n", $lines),
    $readmeContent
);

/**
 * WRITE NEW README
 */


file_put_contents($readmeFilePath, $readmeContent);
